services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=illnevertell
      - POSTGRES_DB=nutrien
    ports:
      - 5432:5432
    # run `docker-compose down -v` and `docker-compose up --force-recreate` to reset the database
    # volumes: db:/var/lib/postgresql/data

  service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Great place to swap out the real username+pw for Secrets Manager (above too). DB must match the POSTGRES_DB up above.
      DATABASE_URL: postgres://postgres:illnevertell@db:5432/nutrien
      SERVER_PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      # Creates an anonymous volume so we don't overwrite the Dockerfile `npm i` step, which installs `@esbuild/linux-arm64` bindings for
      # `tsx` to use instead of the `@esbuild/darwin-arm64` bindings intalled for OSX.
      - /app/node_modules
    depends_on:
      - db
